[project]
name = "aiomonad"
version = "0.0.0.dev0+2025.7.23"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src/main/python"]
include = ["aiomonad"]

[dependency-groups]
dev = [
    "mypy>=1.17.0",
    "pytest>=8.4.1",
    "pytest-asyncio>=1.1.0",
    "pytest-cov>=6.2.1",
    "ruff>=0.12.4",
]

[tool.mypy]
explicit_package_bases = true
mypy_path = [
    "src/main/python",
]

[tool.ruff.lint]
select = ["E", "F", "I"]
